DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_l_16_224
  VIT:
    PATCHES: 16
    EMBED_DIM: 1024
    FEEDFORWARD_DIM: 4096
    NUM_HEADS: 16
    NUM_LAYERS: 24
    ATTENTION_DROPOUT_RATE: 0.0
    DROPOUT_RATE: 0.1
    REPRESENTATION_SIZE: 1024
    CLASSIFIER: 'token'
    POSITIONAL_EMBEDDING: '1d'
SAVE_FREQ: 50
