DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_b_32_224
  VIT:
    PATCHES: 32
    EMBED_DIM: 768
    FEEDFORWARD_DIM: 3072
    NUM_HEADS: 12
    NUM_LAYERS: 12
    ATTENTION_DROPOUT_RATE: 0.0
    DROPOUT_RATE: 0.1
    REPRESENTATION_SIZE: 768
    CLASSIFIER: 'token'
    POSITIONAL_EMBEDDING: '1d'
SAVE_FREQ: 50
