DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_b_16_224_ft
  VIT:
    PATCHES: 16
    EMBED_DIM: 768
    FEEDFORWARD_DIM: 3072
    NUM_HEADS: 12
    NUM_LAYERS: 12
    ATTENTION_DROPOUT_RATE: 0.0
    DROPOUT_RATE: 0.1
    REPRESENTATION_SIZE: 768
    CLASSIFIER: 'token'
    POSITIONAL_EMBEDDING: '1d'
TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 15