DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: resnet
  NAME: resnet152_Ft
  RESNET:
    LAYERS: [3, 8, 36, 3]
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 15
