DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: convnext
  NAME: convnext_base
  DROP_PATH_RATE: 0.2
  CONVNEXT:
    DIMS: [128, 256, 512, 1024]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
SAVE_FREQ: 50
