DATA:
  DATASET: agri430k
  IMG_SIZE: 224
MODEL:
  TYPE: convnext
  NAME: convnext_tiny
  DROP_PATH_RATE: 0.1
  CONVNEXT:
    DIMS: [96, 192, 384, 768]
    DEPTHS: [ 3, 3, 9, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
SAVE_FREQ: 50
